Mark/462 s3 upload
regen-network/registry-server pull request #102
Opened 2021-11-18 06:02 UTC by mhagel

## Description

Closes wtih front end PR: regen-network/regen-registry#462

Endpoints to upload to S3 or delete from S3. 
/images route

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] targeted `dev` branch
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all tests passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2021-11-23 03:39 UTC, haveanicedavid requested changes
Code looks good, but I'm having trouble running locally. That might just be something with my new computer setup, but the main branch does seem to run so I'm not sure

It seems to be caused by the `File` type definition in `/routes/images.ts`: 
```
registry-server: TSError: ⨯ Unable to compile TypeScript:
registry-server: routes/images.ts(22,13): error TS2304: Cannot find name 'File'.
```

which looks to be imported by TS's Dom library (which server code might not have access to?). Could you use a different type definition?

2021-11-23 03:39 UTC, haveanicedavid commented on server/routes/images.ts
> +      data: File,
This type definition seems to be the culprit

2021-11-23 09:12 UTC, blushi commented on server/Server.ts
> +app.use(require('./routes/images'));
I wouldn't name this `/images` but rather `/upload` because it's not only meant for uploading images, this can be used also for uploading project kml files, etc.

2021-11-23 09:52 UTC, blushi commented on server/routes/images.ts
> +      data: File,
yeah I also get `Cannot find name 'File'.`
this seems to help: https://github.com/IBM/node-sdk-core/issues/9#issuecomment-483523620

2021-11-23 09:54 UTC, blushi commented on server/routes/images.ts
> +      response.send('File succesfully deleted')
```suggestion
      response.send('File successfully deleted')
```

2021-11-23 20:43 UTC, mhagel commented on server/Server.ts
> +app.use(require('./routes/images'));
maybe `/file` since it also has a delete route?

2021-11-23 20:43 UTC, mhagel commented on server/routes/images.ts
> +      response.send('File succesfully deleted')
thanks

2021-11-23 20:43 UTC, mhagel commented on server/routes/images.ts
> +      data: File,
thanks

2021-11-24 00:49 UTC, haveanicedavid approved these changes

2021-11-24 07:59 UTC, blushi commented on server/routes/file.ts
> +router.delete('/images/:projectId/:key', bodyParser.json(), (request, response: express.Response) => {
```suggestion
router.delete('/file/:projectId/:key', bodyParser.json(), (request, response: express.Response) => {
```

2021-11-24 08:01 UTC, blushi commented on server/Server.ts
> +app.use(require('./routes/images'));
what about using plural instead `/files`?

2021-11-24 17:07 UTC, mhagel commented on server/Server.ts
> +app.use(require('./routes/images'));
sounds good

2021-11-24 17:07 UTC, mhagel commented on server/routes/file.ts
> +router.delete('/images/:projectId/:key', bodyParser.json(), (request, response: express.Response) => {
done

2021-11-24 17:13 UTC, blushi approved these changes

2021-11-24 17:40 UTC, merged