Add an insert flag to iri-gen command
regen-network/registry-server pull request #127
Opened 2022-03-03 21:54 UTC by wgwz

## Description

Closes: https://github.com/regen-network/regen-registry/issues/848

This adds a flag called `--insert` to the `iri-gen` command. The most important file to review is `iri-gen/index.ts`.

There are few expected outputs for this command:

1. When you run the command and it successfully creates a new entry in the database:
```
kyle@lookfar4:~/regen/registry-server/iri-gen$ yarn gen --insert sample.json                                                                              
yarn run v1.22.15                                                                                                                                         
$ ts-node index.ts --insert sample.json                                                                                                                   
The IRI for sample.json is: regen:13toVhnFSGhv3xdoG4D4pJoBkji8Fp17PuvSoRpE2CWTpKxEyaogdm1.rdf                                                             
Inserting IRI, and metadata into metadata_graph table.                                                                                                    
IRI and metadata inserted successfully.                                                                                                                   
Done in 2.88s.                                     
```

2. When you run the command and it exits because of uniqueness constraints (meaning the IRI already exists):
```
kyle@lookfar4:~/regen/registry-server/iri-gen$ yarn gen --insert sample.json
yarn run v1.22.15
$ ts-node index.ts --insert sample.json
The IRI for sample.json is: regen:13toVhnFSGhv3xdoG4D4pJoBkji8Fp17PuvSoRpE2CWTpKxEyaogdm1.rdf
Inserting IRI, and metadata into metadata_graph table.
error: duplicate key value violates unique constraint "metadata_graph_pkey"
    at Parser.parseErrorMessage (/home/kyle/regen/registry-server/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/kyle/regen/registry-server/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/kyle/regen/registry-server/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/kyle/regen/registry-server/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 272,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (iri)=(regen:13toVhnFSGhv3xdoG4D4pJoBkji8Fp17PuvSoRpE2CWTpKxEyaogdm1.rdf) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'metadata_graph',
  column: undefined,
  dataType: undefined,
  constraint: 'metadata_graph_pkey',
  file: 'nbtinsert.c',
  line: '570',
  routine: '_bt_check_unique'
}
Done in 2.91s.
```

3. When you do not use the flag, you just get the IRI and nothing happens with the database:

```
kyle@lookfar4:~/regen/registry-server/iri-gen$ yarn gen sample.json
yarn run v1.22.15
$ ts-node index.ts sample.json
The IRI for sample.json is: regen:13toVhnFSGhv3xdoG4D4pJoBkji8Fp17PuvSoRpE2CWTpKxEyaogdm1.rdf
Done in 2.95s.
```

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted `dev` branch
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all tests passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2022-03-04 07:54 UTC, blushi commented on iri-gen/.env-example
> +DATABASE_URL=postgres://postgres:postgres@localhost:5432/regen_registry
maybe let's just leave it empty? Since the `connectionString` will default to the local db anyway
and add a comment to use local, staging or production db (for staging/production, getting the info from Heroku) depending on your needs

2022-03-04 14:49 UTC, blushi commented on iri-gen/index.ts
> +  }
what about using something like https://www.npmjs.com/package/minimist instead of this hack?

2022-03-04 14:59 UTC, blushi commented on iri-gen/index.ts
> +  if (insert_flag) {
I guess this should be part of the condition `if (iri)` from above, ie do not try to insert if iri is not defined somehow

2022-03-04 14:59 UTC, blushi commented on iri-gen/index.ts
> +    }
in which case will this error? I'm not sure if the try/catch is actually needed here

2022-03-04 14:59 UTC, blushi commented on iri-gen/index.ts
> +    }
I don't believe this can actually be reached because of the previous `process.exit(0);` 
we should probably exit in `finally` instead?

2022-03-04 14:59 UTC, blushi commented on iri-gen/index.ts
> +    } catch(err) {
```suggestion
    } catch (err) {
```

2022-03-04 16:45 UTC, wgwz commented on iri-gen/.env-example
> +DATABASE_URL=postgres://postgres:postgres@localhost:5432/regen_registry
yup, also made this an empty value

2022-03-04 16:48 UTC, wgwz commented on iri-gen/index.ts
> +  if (insert_flag) {
good catch, how about just changing line 45 to say `if (iri && insert_flag)`?

2022-03-04 16:52 UTC, wgwz commented on iri-gen/index.ts
> +    }
i'm forgetting why i added this here :laughing: i'll remove it for now.

2022-03-04 17:04 UTC, wgwz commented on iri-gen/index.ts
> +    }
good catch! i was not aware of that behavior in js. i've adjusted this so process.exit gets called only after the clean up actions get run.

2022-03-04 17:06 UTC, wgwz commented on iri-gen/index.ts
> +  }
sure! i like that idea. i looked at a few libraries but they all seemed to heavy. this seems like a nice minimal addition, that would make further changes to our cli easier.

2022-03-04 17:57 UTC, wgwz commented on iri-gen/index.ts
> +  }
converting over to minimist worked very nicely! i'm going to resolve this comment for now. we're now using minimist to parse args.

2022-03-04 18:08 UTC, wgwz commented on iri-gen/index.ts
> +  if (insert_flag) {
i'm going to mark this as resolved for now but let me know if you have any other thoughts on that. i went with what i mentioned and pushed a commit for that.

2022-03-07 07:51 UTC, blushi commented on iri-gen/index.ts
> +  if (insert_flag) {
I think the following would make more sense since it avoids checking for `iri` value again. Also let's use camelCase for naming variables.
```
if (iri) {
  console.log(...)
  if (insertFlag) {
    ...
  }
}
```

2022-03-07 22:48 UTC, wgwz commented on iri-gen/index.ts
> +  if (insert_flag) {
Good point! I made these changes.

2022-03-08 09:08 UTC, blushi requested changes

2022-03-08 09:08 UTC, blushi commented on iri-gen/index.ts
>  }
ideally this part could actually be shared between `iri-gen` and `server` packages

2022-03-08 09:08 UTC, blushi commented on iri-gen/index.ts
> +}
seems like the indentation is not consistent with the rest of the file in here
can't wait to get linting setup ;)

2022-03-08 09:08 UTC, blushi commented on iri-gen/index.ts
> +    return {doc, iri};
```suggestion
    return { doc, iri };
```

2022-03-08 09:08 UTC, blushi commented on iri-gen/index.ts
> +  const {iri, doc} = await readFileAndGenerateIRI(path);
```suggestion
  const { iri, doc } = await readFileAndGenerateIRI(path);
```

2022-03-08 09:08 UTC, blushi commented on iri-gen/index.ts
> +        var client = await pool.connect();
let's use ES6 everywhere
```suggestion
        const client = await pool.connect();
```

2022-03-08 09:08 UTC, blushi commented on iri-gen/index.ts
> +        client.release();
```suggestion
        if (client) client.release();
```

2022-03-08 09:08 UTC, blushi commented on iri-gen/package.json
> +    "dotenv": "^16.0.0",
dotenv is also in server/package.json, maybe let's just use the same version everywhere and have it in the root package.json?

2022-03-08 09:08 UTC, blushi commented on iri-gen/package.json
> +    "pg": "^8.7.3",
ditto

2022-03-08 18:11 UTC, wgwz commented on iri-gen/.env-example
> +# NODE_ENV must be set to production if you are running against production
ah, ok. that makes sense and it also explains why i was getting a certain error when i was trying to connect to the staging database from my local environment.

2022-03-08 18:18 UTC, wgwz commented on iri-gen/index.ts
>  }
yeah, i wasn't quite sure how connected we wanted these packages to be. that also relates to why i chose to install the dotenv and pg dependencies within the iri-gen package rather than shared `package.json`. i was thinking that maybe you wanted to keep these packages somewhat independent. but the LOC above definitely do link them now. how do you think we should address sharing this code between the packages?

the first idea that comes to mind for me is that we could created a `common` package. and then within that we could have shared things. maybe the first module would be a `utils.ts` module. and then this function could be imported from there.

2022-03-08 18:23 UTC, wgwz commented on iri-gen/package.json
> +    "dotenv": "^16.0.0",
yeah, so i wasn't sure how isolated we wanted `iri-gen` and the `server` package to be. that said, i can't think of a strong reason why we would want to manage these dependencies separately. if we move these into the shared `package.json` it will probably easier to manage upgrading dependencies. will make this change, thanks for raising this :)

2022-03-09 05:45 UTC, S4mmyb reviewed
Hi @wgwz! Thanks for the PR, I mainly just reviewed for general content and will defer to @blushi  for specific changes. Given you get her ok I think this looks great. Looking forward to the even simpler iri-gen

2022-03-09 08:18 UTC, blushi commented on iri-gen/index.ts
>  }
having a common package sounds good to me

2022-03-09 23:12 UTC, wgwz commented on iri-gen/.env-example
> +# NODE_ENV must be set to production if you are running against production
i've removed the comment and uncommented the NODE_ENV variable. agreed that this is simplest.

2022-03-09 23:15 UTC, wgwz commented on iri-gen/index.ts
> +    return {doc, iri};
done!

2022-03-09 23:16 UTC, wgwz commented on iri-gen/index.ts
> +  const {iri, doc} = await readFileAndGenerateIRI(path);
done!

2022-03-11 20:20 UTC, wgwz commented on iri-gen/index.ts
>  }
@blushi done! at least in terms of a minimal proof-of-concept. let me know what you think. i'm going to resolve this issue for now, and open a new thread on where i've made the changes.

2022-03-11 20:21 UTC, wgwz commented on common/utils.ts
> +export { pgPool };
here is the new module. i chose a simple name for now, but i am open to changing this name or even adding. i like `common` but maybe there is a better choice for `utils`, like `dbutils`?

2022-03-11 20:22 UTC, wgwz commented on iri-gen/index.ts
>          console.log('IRI and metadata inserted successfully.');
this is was the function that i had to pull out into the new common module. i adjusted import statement and made small name change to be consistent.

2022-03-11 20:24 UTC, wgwz commented on package.json
> +    "common"
i had to add the new module to the workspaces, this allowed simpler import statements throughout the code. i.e. `import 'common/utils` vs `../common/utils`

2022-03-11 20:25 UTC, wgwz commented on server/pool.ts
>  exports.runnerPromise = runnerPromise;
i decided to still keep this module, and keep the `runnerPromise` available here. it's only used in `server`.

2022-03-11 20:26 UTC, wgwz commented on server/routes/auth.ts
use the new common module instead...

2022-03-11 20:26 UTC, wgwz commented on server/routes/metadata-graph.ts
> +import { pgPool } from 'common/utils';
use the new common module instead...

2022-03-11 20:26 UTC, wgwz commented on server/routes/stripe.ts
> +import { pgPool } from 'common/utils';
use the new common module instead...

2022-03-14 13:03 UTC, blushi commented on server/pool.ts
>  import * as fs from 'fs';
unused
```suggestion
```

2022-03-14 13:03 UTC, blushi commented on server/pool.ts
>  exports.runnerPromise = runnerPromise;
probably best to rename this file to `runner`

2022-03-15 07:41 UTC, blushi approved these changes
LGTM

2022-03-15 15:48 UTC, haveanicedavid approved these changes

2022-03-15 18:13 UTC, merged