onChainId migration with index
regen-network/registry-server pull request #129
Opened 2022-03-05 00:02 UTC by mhagel

## Description

Part of: regen-network/regen-registry#805
Pairs with [#857](https://github.com/regen-network/regen-web/pull/857)

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] targeted `dev` branch
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all tests passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2022-03-07 08:03 UTC, blushi requested changes

2022-03-07 08:03 UTC, blushi commented on sql/V1_82__add_on_chain_id_to_credit_class.sql
> +create index on project("handle");
this was already there as part of V1_30 migration
could you remove this?

2022-03-08 16:38 UTC, mhagel commented on sql/V1_82__add_on_chain_id_to_credit_class.sql
> +create index on project("handle");
omg this is a mistake

2022-03-08 17:38 UTC, mhagel commented on README.md
> +CREATE DATABASE regen_registry;
When I have to restore my DB, I run into problems if I `DROP ROLE app_user;` after `CREATE DATABASE regen_registry;`

But doing it in this order works.

2022-03-08 18:07 UTC, blushi approved these changes

2022-03-08 18:59 UTC, wgwz approved these changes

2022-03-08 19:06 UTC, merged