kyle/897 api endpoints for gen iri
regen-network/registry-server pull request #169
Opened 2022-04-13 21:47 UTC by wgwz

- Clean up server tests db helpers module
- Adds /iri-gen endpoint

2022-04-13 21:50 UTC, wgwz commented on server/routes/metadata-graph.ts
> +});
this is the new GET endpoint. the semantics is technically a little weird here, and a REST purist may not like this. it's a GET request that expects a JSON body. that JSON body is the "metadata"

2022-04-13 21:51 UTC, wgwz commented on server/routes/metadata-graph.ts
> +});
this is the new POST endpoint. it expects a JSON body which would be the "metadata", and it idempotently inserts the metadata.

2022-04-13 21:54 UTC, wgwz commented on common/metadata_graph.ts
> +  },
here's the idempotent insert, it's a bit of hack because of how it updates the values on conflict. the reason i made this update on conflict instead of do nothing on conflict is because i want it to return the iri and metadata each time. without updates, you don't get back the values in the `RETURNING` part of the SQL statement. it's a little hacky, but it works and i don't think it can cause us problems (given how iri's uniquely identify a metadata).

2022-04-13 21:55 UTC, wgwz commented on common/metadata_graph.ts
> +  },
I think I may adapt the current `/metadata-graph/:iri` endpoint to make use of this...

2022-04-13 21:57 UTC, wgwz commented on iri-gen/__tests__/iri-gen.test.ts
> +  });
@blushi this was that test scenario (invalid json-ld leading to an empty string) i mentioned in our architecture call earlier today. let me know what you think about the ergonomics of this, but i feel like the right thing to do at this level is to just have the function throw, and let the higher-level code catch.

2022-04-13 21:58 UTC, wgwz commented on iri-gen/index.ts
> +        await MetadataGraph.insert_iri_doc(client, iri, doc);
i restructured this a little bit to make use of the common code

2022-04-13 21:58 UTC, wgwz commented on iri-gen/iri-gen.ts
> +    throw new Error('Invalid JSON-LD document');
the new throw, when an invalid json-ld document was encountered

2022-04-14 07:14 UTC, blushi commented
@wgwz could you make sure to link the issue it closes? thanks

2022-04-14 07:24 UTC, blushi requested changes

2022-04-14 07:24 UTC, blushi commented on common/metadata_graph.ts
> +  insert_iri_doc: async function (
let's use camelCase please

2022-04-14 07:24 UTC, blushi commented on common/metadata_graph.ts
> +export const MetadataGraph = {
I don't see how this is useful to declare this as a const vs individual functions with the current design.
A better approach would be to declare this `MetadataGraph` as a class and the `client` would be a private field within this class. This way you don't need to pass the client every time as part of the functions params.

2022-04-14 07:24 UTC, blushi commented on iri-gen/iri-gen.ts
> -  try {
let's keep the try/catch

2022-04-14 12:55 UTC, wgwz commented on common/metadata_graph.ts
> +export const MetadataGraph = {
i just wanted to have a way to have the functions have a namespace, which is more style/preference than utility. i’ll switch to a class though, it’s better i agree.

2022-04-14 12:59 UTC, wgwz commented on iri-gen/iri-gen.ts
> -  try {
could you explain this more? i’m having trouble understanding why a catch-all try/catch is used in this low-level of the code. in my past experience, i have learned the style of letting errors propagate to your highest-level calls. i.e. within a router.

2022-04-14 14:29 UTC, blushi commented on iri-gen/iri-gen.ts
> -  try {
we've got some `await` in there which could throw an error that we should catch
for instance, `generateIRI` is used directly in `router.get('/iri-gen')
if an error happens then, that would just crash the server.

2022-04-14 14:34 UTC, blushi commented on iri-gen/iri-gen.ts
> -  try {
just try `curl http://localhost:5000/iri-gen` without any req body for instance

2022-04-14 16:04 UTC, wgwz commented on iri-gen/iri-gen.ts
> -  try {
ah, ok. thanks for that. so i thought about this a little bit. i think i've found a nice way for us to handle this. i'm going to push up the changes, and then add comments that will hopefully tell the story.

2022-04-14 16:19 UTC, wgwz commented on server/Server.ts
> +app.use((err, req, res, next) => {
this is hooking into the express error handling tools. this error handler will intercept any exceptions raised in synchronous routes, or from asynchronous routes which correctly handle errors. https://expressjs.com/en/guide/error-handling.html

within this error handler you will notice that we introduce specific logic for certain types of exceptions, i.e. `MetadataNotFound` and `InvalidJSONLD`.

if any other error occurs, you will notice the else block saying `next(err)`. this passes any unhandled errors along to the default express error handler, which will result in a 500 error. generally, that is what we want to happen.

FYI - in express v4 which is what we are using, there is a specific way you must handle errors in async routes. I'll be adding another comment highlighting that. However, in express v5, no extra work will be required, and sync/async routes will work the same way (see the docs above for more).

2022-04-14 16:25 UTC, wgwz commented on server/routes/metadata-graph.ts
> +router.get('/iri-gen', async (req, res, next) => {
this router is a concise example of errors from an *async* express route can be handled by the express error routing system. notice how within this route we make a call to `next(err)`. this call makes the execution flow go to any user-defined error handlers (if present) or it results in the exception being sent to the default express error handling system. in the current state of the code here, it would be sent to the error handlers i defined (which was mentioned in a previous comment).

one reason this is nice, is because you don't need to worry about sending 500 internal server errors. i personally also like how when you use the custom error handlers, you can modify responses to be more ergonomic, but also centralized logic related to errors.

2022-04-15 15:33 UTC, wgwz commented on common/metadata_graph.ts
> +export const MetadataGraph = {
Made this switch via 4676d9ca9f90e802dbba5cbbf84490ffe1f4d99b and I think it's much better, thanks for the suggestion. It's better in terms of ergonomics and type safety

2022-04-20 22:04 UTC, mhagel approved these changes
LGTM

2022-04-20 22:04 UTC, mhagel commented on server/routes/metadata-graph.ts
> +router.get('/iri-gen', async (req, res, next) => {
Cool. Thanks for the explanation.

2022-04-22 14:21 UTC, blushi commented on server/routes/metadata-graph.ts
> +    const metadata = await MetadataGraph.fetchByIri(client, iri);
seems like this file hasn't been updated to use `MetadataGraph` as a class
when running `yarn serve` or `yarn dev`, the server just crashes

2022-04-22 15:04 UTC, blushi commented
Could you fix the conflicts? @wgwz Thanks

2022-04-22 16:09 UTC, wgwz commented on server/routes/metadata-graph.ts
> +    const metadata = await MetadataGraph.fetchByIri(client, iri);
whoops! forgot to update this, just took care of this via https://github.com/regen-network/registry-server/pull/169/commits/5730f87cd5bff555b2ef8715a84eab2246d76ac3

2022-04-26 08:17 UTC, blushi requested changes

2022-04-26 08:17 UTC, blushi commented on iri-gen/index.ts
> +        await MetadataGraph.insertIriDoc(client, iri, doc);
If I just try to run `yarn gen some-data.json` from `iri-gen` folder, it doesn't work anymore because of this
this should instantiate a new `MetadataGraph` class instead

2022-04-26 08:28 UTC, blushi commented on server/Server.ts
> +app.use((err, req, res, next) => {
should we create an issue to upgrade to express v5 at some point?

2022-04-27 17:14 UTC, wgwz commented on iri-gen/index.ts
> +        await MetadataGraph.insertIriDoc(client, iri, doc);
whoops, fixed this via 9cfe3b2ea12f4f1d8e8a2517522af322a628e1c2. this is making a good case to write some tests that actually run our CLI, but maybe later.

2022-04-27 17:35 UTC, wgwz commented on common/jest.config.js
> +  testEnvironment: 'node',
yup, good call and sorry it took so long to reply on this one. i've implemented this via 5eae86d6bd190d527d4783095e536f5282ef7b5a.

2022-04-27 17:37 UTC, wgwz commented on server/Server.ts
> +app.use((err, req, res, next) => {
sure! i'll write up some notes, IIRC there is still some time before it is officially released, but good to have an issue.

2022-04-27 18:05 UTC, wgwz commented on server/Server.ts
> +app.use((err, req, res, next) => {
https://github.com/regen-network/regen-web/issues/921

2022-04-28 06:56 UTC, blushi approved these changes
Pre-approving, pending a small improvement

2022-04-28 06:56 UTC, blushi commented on iri-gen/index.ts
> +    client = await pgPool.connect();
could we still initialize the client only when needed, ie only if `insertFlag` is true?

2022-04-28 14:04 UTC, wgwz commented on iri-gen/index.ts
> +    client = await pgPool.connect();
yup we could, made that tweak. thanks for catching that

2022-04-28 14:06 UTC, merged