Use either TLS/non-TLS TCP to connect to Redis
regen-network/registry-server pull request #177
Opened 2022-04-29 17:25 UTC by wgwz

## Description

Closes: https://github.com/regen-network/regen-registry/issues/867

- Depending on the redis connection string, we will connect
  to redis using either TLS or non-TLS.
- A redis connection string that starts with redis:// is
  a non-TLS TCP connection.
- Whereas a connection string that starts with rediss:// is
  a TLS TCP connection.
- ioredis is added as a dependency to make this work with
  the express-sharp library.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted `dev` branch
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2022-04-29 17:42 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +      keyvRedis = new KeyvRedis(redis, options);
here is how i tested these changes locally.

```
./src/redis-server --tls-port 6379 --port 0 --tls-cert-file ./utils/tests/tls/redis.crt --tls-key-file ./utils/tests/tls/redis.key --tls-ca-cert-file ./utils/tests/tls/ca.crt --tls-auth-clients no
```

The command above gets a redis instance running locally with TLS.

```
➜  server git:(kyle/867-redis-tls) ✗ yarn start                        
yarn run v1.22.15
$ ts-node Server.ts
Attempting to connect to Redis with TLS..
Using S3 image adapter
[HPM] Proxy created: /  -> http://185.181.11.150:26657/
[HPM] Proxy rewrite rule created: "^/ledger" ~> "/"
[HPM] Proxy created: /  -> http://185.181.11.150:1317/
[HPM] Proxy rewrite rule created: "^/ledger-rest" ~> "/"
Started server on port 5000
Graphiql UI at http://localhost:5000/graphiql
[core] INFO: Worker connected and looking for jobs... (task names: 'credits_transfer__send_confirmation', 'interest_buyers__send_confirmation', 'send_email')
```

After running `yarn start` we can see that indeed, from above, we've gone through the TLS branch (when `REDIS_URL=rediss://localhost:6379`).

In order to test that the image caching is working correctly, we can run a repeated request for a image that should come through the caching service, and we can see that it indeed returns a cached version (based on output from `DEBUG='express*' yarn start`:

```
➜  ~ for i in {1..100..1}; do
  http GET localhost:5000/image/Wilmot5.jpg > /dev/null;
done
```

```
  express:router dispatching GET /image/Wilmot5.jpg +895ms
  express:router query  : /image/Wilmot5.jpg +0ms
  express:router expressInit  : /image/Wilmot5.jpg +0ms
  express:router <anonymous>  : /image/Wilmot5.jpg +0ms
  express:router corsMiddleware  : /image/Wilmot5.jpg +0ms
  express:router middleware  : /image/Wilmot5.jpg +0ms
  express:router jsonParser  : /image/Wilmot5.jpg +0ms
  express:router trim prefix (/image) from url /image/Wilmot5.jpg +0ms
  express:router router /image : /image/Wilmot5.jpg +1ms
  express:router dispatching GET /Wilmot5.jpg +0ms
  express-sharp:transformer Serving Wilmot5.jpg from cache ... +896ms
```

this process works exactly the same when you switch to redis running with non-TLS and make an update to the `REDIS_URL=redis://localhost:6379`

because the code can successfully run for either TLS or non-TLS redis, once we deploy this code to staging, it will work without issue for the current redis instance. and i believe that once i upgrade the staging redis to a higher tier, our code will be able to seamlessly adjust to the change.

2022-04-29 20:06 UTC, wgwz commented
I'm going to expand the scope of this PR a little bit. I just discovered that there was a memory leak in express-sharp which affects the version we are currently using. I'm going to upgrade express-sharp to the latest version as a part of this PR (since I'm already testing that with the redis upgrade task).

https://github.com/pmb0/express-sharp/commit/f1a88496dd2d117dacf79738475d974194cca554
https://github.com/pmb0/express-sharp/pull/451

2022-05-02 09:51 UTC, blushi approved these changes

2022-05-02 09:51 UTC, blushi commented on server/middleware/imageOptimizer.ts
> +      // pass tls options there, otherwise it gets overrided.
is this bug referenced somewhere (eg github issue)? if that's the case, it'd be good to mention it in the comment.

```suggestion
      // pass tls options there, otherwise it gets overridden.
```

2022-05-02 09:54 UTC, blushi requested changes
Somehow, when pulling this branch locally and running `yarn`, I get some changes in `yarn.lock` that didn't get commited:
```
-pg-connection-string@^2.0.0, pg-connection-string@^2.5.0:
+pg-connection-string@2.x, pg-connection-string@^2.0.0, pg-connection-string@^2.5.0:
```

2022-05-02 15:23 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +      // pass tls options there, otherwise it gets overrided.
i can take a look to see if it is an issue that's been reported in KeyvRedis.. but i just found it and figured out the workaround.. if i can't find an issue i'll at least add some info here about the type of error i receive

2022-05-02 17:45 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +      // pass tls options there, otherwise it gets overrided.
added a bit more detail to the comments, and then i also opened up an issue in `@keyv/redis`: https://github.com/jaredwray/keyv/issues/308

2022-05-03 06:45 UTC, blushi approved these changes

2022-05-03 19:58 UTC, mhagel approved these changes

2022-05-03 20:26 UTC, merged