Keplr login endpoint
regen-network/registry-server pull request #227
Opened 2022-07-21 00:53 UTC by wgwz

## Description

Closes: https://github.com/regen-network/regen-registry/issues/1051

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] targeted `dev` branch
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2022-07-26 23:18 UTC, wgwz commented on server/Server.ts
> +app.use(cookieSession(cookieSessionConfig));
this is an important addition, see the configuration options above here. see [this section](https://www.notion.so/regennetwork/Registry-Keplr-Login-Notes-049bded66a604410b71f3d3824e2e8fd#cc32d4c58be64b54b0d03326d4bb8430) of the keplr login design doc for why i've implemented this in a cookie session. cookies will contain public info about the user, and they are signed, so they are tamper-proof (assuming a secure secret key). the main benefit of this choice is that it does not require server-side state.

2022-07-26 23:22 UTC, wgwz commented on server/Server.ts
> +initializePassport(app, passport);
another important addition here

2022-07-26 23:24 UTC, wgwz commented on server/Server.ts
> +app.use('/web3auth', web3auth);
the new keplr login system has a prefix of web3auth, so the new endpoints will read:
- /web3auth/login
- /web3auth/logout
- /web3auth/nonce

2022-07-26 23:25 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +export function KeplrStrategy(): CustomStrategy {
this is probably the most important location to review

2022-07-26 23:27 UTC, wgwz commented on server/middleware/passport.ts
> +export function initializePassport(
this function sets up `passportjs`. in the future, other login methods can be added here.

2022-07-26 23:34 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +      const { signature, profileType } = req.body;
note-to-self: think through if it makes sense to have `profileType` as a required parameter here.

2022-07-26 23:34 UTC, wgwz commented on server/routes/web3auth.ts
> +export const web3auth = express.Router();
this router includes the new endpoints for login, logout and nonce.

2022-07-27 15:26 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +      const { signature, profileType } = req.body;
i've create a new issue for this, i think the resolution will be to separate account creation from the login process. https://github.com/regen-network/regen-registry/issues/1084

2022-07-27 17:30 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +      const { signature, profileType } = req.body;
the issue mentioned in my last comment is being closed because we are now preferring a simpler solution. by default we will always create "user" type profiles for new accounts.

so that means that when a user clicks "login", we will either log them in or create a new account for them. that new account will always be given "user" profile type.

therefore at present, this parameter can be removed from this endpoint and we can hard-code a value of "user".

2022-07-27 20:03 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +      const { signature, profileType } = req.body;
resolved via 024710d

2022-07-27 20:23 UTC, wgwz commented
i've opened these issues as next steps and they can be addressed in separate PRs:

- https://github.com/regen-network/regen-registry/issues/1078
- https://github.com/regen-network/regen-registry/issues/1079
- https://github.com/regen-network/regen-registry/issues/1080
- https://github.com/regen-network/regen-registry/issues/1086

2022-08-01 17:53 UTC, wgwz commented
@amaurym i just wanted to note that i added you here as a reviewer with the intent of you being an optional reviewer. this is work that i did based on the review you helped me with in the PoC ([here](https://github.com/wgwz/simple-express-keplr-passport/pull/1) and [here](https://github.com/wgwz/simple-express-keplr-passport/pull/2) for others). please feel free to optionally review, thanks!

2022-08-01 18:29 UTC, haveanicedavid approved these changes

2022-08-01 18:34 UTC, wgwz commented
@frumioj i wanted to add you as an optional reviewer as well. since this is an auth system where security is extra important i wanted to have another experienced eye to review. if you have time, this would be greatly appreciated. FYI - i also pinged you in regen slack (don't expect you to be regularly checking there but thought it would be good to reach out in two places). thanks!

2022-08-01 19:42 UTC, mhagel commented on sql/V2_15__add_nonce_to_account.sql
> +DO $$
Just gotta update this name

2022-08-01 19:53 UTC, mhagel approved these changes

2022-08-02 10:53 UTC, amaurym commented on server/middleware/keplrStrategy.ts
> +          nonce: nonce,
I would extract this object into a separate constant/function, it's used twice in this file

2022-08-02 10:53 UTC, amaurym commented on server/routes/web3auth.ts
> +  // have this public.
Maybe it's worth noting that there's a tiny privacy issue too. If I know your public address, then I can call `/nonce?userAddress={your_address}`. And I'll know whether or not you've already signed up on Regen.

2022-08-02 10:53 UTC, amaurym commented on server/middleware/keplrStrategy.ts
> +        });
This introduces a security risk IMO. The whole security of this login relies on the user signing a piece of data that the backend generates randomly.

Here, if the signing payload is static, then a malicious actor can trick the user to sign this piece of static text, copy the sig, and log in as the victim.

2022-08-02 10:53 UTC, amaurym commented on server/middleware/keplrStrategy.ts
> +        });
Maybe it's worth exploring a `/signup` endpoint for creating accounts. The frontend flow would be:
- check `/nonce`
  - if it's a 404, then call `/signup`, this can return the whole user object, including nonce.
  - if not, then we get back nonce
- call `/login` after signing the nonce.

This way the frontend _always_ signs a nonce generated by the backend.

2022-08-02 11:04 UTC, amaurym commented
Would also love to have @frumioj's approval before we move on with this. I don't think this login flow has ever been used in production (though some people were talking about it).

One attack vector I believe is worth thinking about is phishing. If a malicious attacker creates `https://reegen.network` (notice the typo), tricks people to come there and login with Keplr, then they'll get access to all tricked victims' signatures, and will be able to log in into their account on the real Regen Network website. This is not inherent to this login flow though, and already exists with regular txs, but worth pointing out.

2022-08-02 22:32 UTC, wgwz commented on server/routes/web3auth.ts
> +  // have this public.
From my understanding, which is based on what I was told by @erikalogie in terms of the design, is that we intend for profiles to be public. So I don't think that this would be an issue, but I suppose if we wanted to obfuscate this we could. I.e. instead of a returning a 404 when a nonce is not found, we could always return a nonce (in the exact same format). This would fix the privacy concern, but make a new issue in terms of ease of use for the client-side. But of course, if there are going to be public profiles, it's likely there is another way to determine whether or not an address has signed up on regen.

2022-08-03 00:23 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +        });
@amaurym The empty nonce here felt like a risk to me as well but I couldn't figure out why. Thanks for explaining that and for catching it! I think I am basically in agreement with you that we should always have a valid nonce in the signing data. Writing some thoughts, please let me know if I'm missing anything.

In what you're proposing would the `/signup` endpoint still require a signature? That endpoint definitely has to be public and accept an address in order to work. If we require a signature here, it obviously could not include a nonce at this stage, so it would have to be a signature of static data. This would prevent easily scripting fake accounts and filling our database with fake accounts.

The important difference with the proposed approach and the current implementation is that a malicious actor could not login as a user with purely static signing data after account creation. The only way to login with the proposed approach is to sign data that includes the nonce. Obviously even this could be vulnerable to phishing like you mentioned in your other comment but it's probably much less likely.

I suppose if we wanted to be extra secure, maybe we need to consider other forms of MFA, like text or email? It really is analogous to phishing for google passwords via email or advertisements, and I know at present various MFA methods are best-practices. FWIW, I don't think commonwealth has MFA.

2022-08-03 00:36 UTC, wgwz commented on server/Server.ts
> +app.use(cookieSession(cookieSessionConfig));
an additional idea is that we could a signature in addition to the address for the nonce endpoint. this would restrict the lookup only to a valid signature and the address attached to that signature. i think this could also be a way to still maintain a single login button (per the designs)

2022-08-03 02:25 UTC, wgwz commented on server/routes/web3auth.ts
> +  // have this public.
an additional idea is that we could a signature in addition to the address for the nonce endpoint. this would restrict the lookup only to a valid signature and the address attached to that signature. i think this could also be a way to still maintain a single login button (per the designs)

2022-08-03 09:12 UTC, amaurym commented on server/middleware/keplrStrategy.ts
> +        });
> In what you're proposing would the /signup endpoint still require a signature? (...) so it would have to be a signature of static data. This would prevent easily scripting fake accounts and filling our database with fake accounts.

How would this prevent fake sign-ups? I can create a script which creates dummy accounts (not on Keplr, but in a bash script) signs this static data and then pings the /signup API. This is why I think a signature on signup is not useful.

Apart from MFA, I unfortunately can't think of anything to prevent fake signups. Maybe IP rate limiting, but that's not perfect.

I personally feel more and more that @frumioj's input would be useful: to define Regen's threat model. This way we can decide whether the attacks we defined above (phishing, fake accounts) are okay to have or not.

2022-08-03 10:42 UTC, erikalogie commented on server/routes/web3auth.ts
> +  // have this public.
Yes we intend for profiles to be public for users who signed up on the app, same as what OpenSea does.

2022-08-03 14:11 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +        });
I was mixing up the scenarios where an actor creates an account on behalf of a user vs. an actor just creating fake addresses and signatures. Indeed, we are still susceptible to fake account creation in the latter scenario. But wouldn’t we have some added protection in former?

2022-08-03 14:57 UTC, amaurym commented on server/middleware/keplrStrategy.ts
> +        });
So if I understand the former: I (malicious) can create an account with your (victim) public address, and your public profile will show up on Regen, even though you never interacted with Regen. But I cannot login into your account.

I think that's okay security-wise. But maybe that's a product decision too (i.e. define threat models). If the above scenario is not okay to have, then adding an additional signature on signup is a good way to go.

2022-08-03 18:30 UTC, frumioj commented
> Would also love to have @frumioj's approval before we move on with this. I don't think this login flow has ever been used in production (edit: Kyle mentioned commonwealth above).
> 
> One attack vector I believe is worth thinking about is phishing. If a malicious attacker creates `https://reegen.network` (notice the typo), tricks people to come there and login with Keplr, then they'll get access to all tricked victims' signatures, and will be able to log in into their account on the real Regen Network website. This is not inherent to this login flow though, and already exists with regular txs, but worth pointing out.

I'll try to review it, but probably not able before the weekend. 

Noting @amaurym 's issue above, I would ask have the threats been written down and discussed in your architecture doc @wgwz ? I no longer have access to Regen Notion and I seem to have lost my Slack access too. I do think it would help to write down the threats if not already done, and discuss mitigations.

2022-08-03 19:40 UTC, wgwz commented
@frumioj thanks! we don’t have a section in the doc with threats written down yet. the ones we’ve been discussing here are kind of the first major issues we have looked at. fortunately we still have plenty of time before this needs to get merged (probably at earliest by the end of September). 

also my time will be limited for this work for the next few weeks as i’m helping out with some other higher priority work related to marketplace features in the registry.

i’ll see if we can add you back to doc @frumioj but perhaps we can just continue the discussions here for now, and then i can look to add the threats/mitigations into the doc. WDYT?

2022-08-07 17:26 UTC, frumioj requested changes
I'd like to review this against the design doc you wrote @wgwz and I'd also like to ensure the challenge for signature is a sufficiently cryptographic random number.

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +        'select a.id, a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
Is it possible for an attacker to specify in $1 the address (which is public right?) and select id and nonce information for another user?

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +            'This is a transaction that allows Regen Network to authenticate you with our application.',
Is the transaction a valid one? Will it appear on-chain? Perhaps "By clicking 'sign' you are consenting to connect your wallet to Regen Network, allowing you to seamlessly login in future by using your keplr wallet address. This transaction will not appear on the Regen Network blockchain. Please review {URL to website describing in detail how the keplr login process works for RN}"

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +          'update account set nonce = md5(random()::text) where id = $1',
Why md5? How random is random() (is it cryptographic random)?

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +            'This is a transaction that allows Regen Network to authenticate you with our application.',
Same comment as the other place where you have the transaction description - should be careful to properly explain what is going on here to the user, and link to a deeper explanation.

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +          nonce: '', // an empty string since this is an account creation login..
Must NOT be empty. And MUST only be used once. Also, this is actually known as a "challenge" (even though it's also a nonce) for authentication, since the client is asked to perform a valid signature in response to the challenge.

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +        });
I do think it would to actually write down in plain text what the threats are in the doc you started @wgwz - as well as diagramming the flow to see how it matches up with the threats.

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +              await client.query(`create role ${address} in role auth_user`);
Can anyone try and specify a $address so a role is created?

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +              'error: this addr belongs to a different account'
Does this error end up being shown to the user? If so, it would help someone who was guessing accounts.

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +            'select a.id, a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
Can $1 be specified by an attacker?

2022-08-07 17:26 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +            'select a.id, a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
Note also for any SQL-like thing - is there any protection against SQL injection?

2022-08-07 17:26 UTC, frumioj commented on server/middleware/passport.ts
> +    // here, as it could potentially expose that info if this is being
How should the private info be handled?

2022-08-07 17:26 UTC, frumioj commented on server/routes/web3auth.ts
> +  // have this public.
@amaury - that's exactly the worry I had - but not privacy alone - can I retrieve any private info (not just their public info) by specifying someone else's address?

2022-08-07 17:26 UTC, frumioj commented on server/routes/web3auth.ts
> +        'select a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
As previous comments, make sure SQL injection is not an issue.

2022-08-07 17:26 UTC, frumioj commented on server/routes/web3auth.ts
> +        'select a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
a.nonce is not actually a nonce ("number used only once"?)

Challenge should be different each time - is it?

2022-08-07 19:57 UTC, Amaury commented on server/routes/web3auth.ts
> +        'select a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
Still not the right @Amaury... 😅

2022-08-09 18:54 UTC, wgwz commented on server/Server.ts
> +  options['credentials'] = true;
the cookie lives in the persons web browser. so it is shared with anyone who has access to that persons browser (primarily the person who authenticated), until the cookie expires or the user logs out. the specific LoC here is added because we want our session to be compatible with CORS (see link on line 68 above).

2022-08-09 18:55 UTC, wgwz commented on server/.env.example
> +SESSION_MAX_AGE_IN_HOURS=24
this was just a value that i set based on a brief convo with @S4mmyb . we can of course adjust this if there is a best practice value or other recommendations.

2022-08-09 18:58 UTC, wgwz commented on server/Server.ts
> +    console.error(err.stack);
in this case, this is all server-side code, so no i don't think there is a significant risk here. and i just double-checked and our server-side logs are protected (behind heroku auth).

2022-08-09 19:00 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +        throw new InvalidLoginParameter('invalid signature parameter');
sure, i'm open to doing this.

2022-08-09 19:17 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +        'select a.id, a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
yes, at present, the address is public in addition to the nonce and anyone can lookup the nonce for a given address with an unauthenticated GET request. 

in this particular LoC, `$1` is the address that has been extracted from the signature. at present, if the attacker gets a user to sign a fake transaction (which included the public nonce and used the same format for the signing data), they would be able to authenticate as that user.

FWIW, the `a.id` can only be visible to the attacker if they successfully authenticated as another user.

2022-08-09 19:20 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +            'select a.id, a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
> Can $1 be specified by an attacker?

yes, but they would have to trick the wallet owner to sign a transaction in order for the LoC pointed at to be run.

2022-08-09 19:23 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +            'select a.id, a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
> Note also for any SQL-like thing - is there any protection against SQL injection?

the query style on the LoC here is called a parametrized query in the node-postgres library, these are protected against sqli: https://node-postgres.com/features/queries#parameterized-query

2022-08-09 19:33 UTC, wgwz commented on server/middleware/passport.ts
> +    // here, as it could potentially expose that info if this is being
the de-serialized user is only about what info becomes available to the server-side code when dealing with a request from an authenticated user. the note here is that you need to be aware of doing something like this:

```
res.send(req.user);
```

i.e. if you add the users password part of the de-serialization process (this is a terrible example because you would never do this), this could be exposed in the response above.

so the policy is be very cautious with de-serialization and `req.user` i guess 🤔

2022-08-09 19:41 UTC, wgwz commented on server/routes/web3auth.ts
> +        'select a.nonce from private.get_account_by_addr($1) q join account a on a.id = q.id',
> Challenge should be different each time - is it?

yup, that's happening at the same place as [this comment](https://github.com/regen-network/registry-server/pull/227/files#r939696574).

> a.nonce is not actually a nonce ("number used only once"?)

see [my reply here](https://github.com/regen-network/registry-server/pull/227/files#r939696574).

2022-08-09 19:56 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +          'update account set nonce = md5(random()::text) where id = $1',
> Why md5? How random is random() (is it cryptographic random)?

no reason, it was the first method i came across for creating a random string. glad to improve on this with suggestions. i'm just seeing this now from [the postgres docs](https://www.postgresql.org/docs/current/functions-math.html):

> The random() function uses a simple linear congruential algorithm. It is fast but not suitable for cryptographic applications; see the [pgcrypto](https://www.postgresql.org/docs/current/pgcrypto.html) module for a more secure alternative. If setseed() is called, the series of results of subsequent random() calls in the current session can be repeated by re-issuing setseed() with the same argument.

i'm not sure how to evaluate what sufficiently random is for this particular use case.

2022-08-09 19:58 UTC, wgwz commented on server/routes/web3auth.ts
> +  // have this public.
@frumioj unless you were able to authenticate as the user, you can't retrieve any other private info.

2022-08-09 20:02 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +            'This is a transaction that allows Regen Network to authenticate you with our application.',
This transaction will not appear on-chain. It's a valid arbitrary data signature per [ADR-036](https://docs.cosmos.network/master/architecture/adr-036-arbitrary-signature.html#context).

2022-08-09 20:04 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +          nonce: '', // an empty string since this is an account creation login..
This was a workaround that I initially thought could be acceptable for account creation. More [in this thread.](https://github.com/regen-network/registry-server/pull/227#discussion_r935411750)

2022-08-09 20:05 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +              await client.query(`create role ${address} in role auth_user`);
Not unless an attacker tricked a user into signing the same exact required data (including our nonce).

2022-08-09 21:16 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +          'update account set nonce = md5(random()::text) where id = $1',
here was my thinking about this being ok for generating a nonce (number used once):

this is generates a large random number:
```
regen_registry=# select random()::text;
       random       
--------------------
 0.6128841027230791
(1 row)
```

this hashes that number into text representation:
```
regen_registry=# select md5(random()::text);
               md5                
----------------------------------
 db56605443da48f551cdb99199322d2c
```

i guess the probability of picking the same number twice is on the order of 10e-16:

```
>>> 1/9999999999999999
1.0000000000000001e-16
```

2022-08-09 22:17 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +          'update account set nonce = md5(random()::text) where id = $1',
Please don't do that. If this is coming from postgres, use pgcrypto to generate something suitable - probably the random bytes would be best: https://www.postgresql.org/docs/current/pgcrypto.html#id-1.11.7.35.10

2022-08-09 22:47 UTC, frumioj commented on server/middleware/keplrStrategy.ts
> +        });
As I understand what @amaurym wrote above (attacker registers you with Regen) I don't think that's OK at all. Regen must have the consent of the user to register with Regen. That is what the initial signature is for. Regen needs to store the fact that the user *consented* to being registered.

2022-08-09 23:07 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +          'update account set nonce = md5(random()::text) where id = $1',
@frumioj Ok, WDYT the code below? Do you have any suggestions on the number of bytes? I've chosen 256 arbitrarily, the maximum value for this function is 1024. I would like to produce a relatively concise/readable nonce, hence the md5 hash still being used here.  

```
regen_registry=# select * from md5(gen_random_bytes(256));
               md5                
----------------------------------
 82c6e5d6dfe15dd00501ce98141ac2e9
```

2022-08-09 23:12 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +          'update account set nonce = md5(random()::text) where id = $1',
Alternatively:

```
regen_registry=# select * from encode(sha512(gen_random_bytes(512)), 'hex');
                                                              encode                                                              
----------------------------------------------------------------------------------------------------------------------------------
 c03cbdd9990cfeef1a1e5d650930a1863590135276dc0729da6d35d09e43347e332c248e0fd3a1f60ef6d71cacf236f7fe8fa612c7614bc347c5242cf4575799
(1 row)
```

2022-09-01 12:03 UTC, wgwz commented
todo: add csrf protection. i.e. a user gets emailed a maliciously crafted link that contained a graphql query to add an address to their account, in the current implementation, if they had active user session, and the malicious link opens in their broswer, the attacker could add an address to the users account, and thereby login as that user.

2022-12-19 19:48 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +        throw new InvalidLoginParameter('invalid signature parameter');
this isn't visible to app users, it's private backend logs, i don't see a reason to change it

2022-12-19 19:53 UTC, wgwz commented on server/middleware/keplrStrategy.ts
> +              'error: this addr belongs to a different account'
nope

2023-03-08 13:27 UTC, blushi reviewed
Looks great, most of the code here has been already reviewed as part of separate PRs but I spotted a few minor stuff that would be good to address before merging.

2023-03-08 13:27 UTC, blushi commented on server/Server.ts
> +};
just a nit, maybe we could extract this part into another file to not bloat this Server.ts too much?

2023-03-08 13:27 UTC, blushi commented on server/routes/web3auth.ts
> +        }
maybe we could simplify the code a little bit
```suggestion
        if (associatedAccount.rowCount === 1) {
          const [{ id: associatedId }] = associatedAccount.rows;
          await client.query(
            'select from private.remove_addr_from_account($1, $2)',
            [associatedId, address],
          );
        }
        await client.query(
          'select from private.add_addr_to_account($1, $2, $3)',
          [currentUserId, address, 'user'],
        );
        return res.status(200).send({ message: 'success' });
```

2023-03-08 13:27 UTC, blushi commented on server/Server.ts
> +app.use('/graphql', doubleCsrfProtection);
is there some way to disable csrf protection for graphiql? it's just not working anymore, always getting "invalid csrf token" error

2023-03-08 13:27 UTC, blushi commented on sql/authn/R__get_current_account_id.sql
> +CREATE OR REPLACE FUNCTION public.get_current_account_id()
why do we need both `get_current_account_id()` and `get_current_account()`? they both return the current account ID

2023-03-09 14:41 UTC, wgwz commented on server/Server.ts
> +};
TBH, i'm not too worried about the number of lines in this file, so i would leave it as is

2023-03-09 14:50 UTC, wgwz commented on server/Server.ts
> +app.use('/graphql', doubleCsrfProtection);
i briefly looked into this but i didn't find anything, i can check again.
i am hoping that graphiql allows you to customize it with some code to run before it loads or something like that.
in our case, if we could add some custom client side code that does our csrf protocol, it would work.
otherwise, we're kind of stuck.
because for me the security concern was outweighing the inconvenience of not having graphiql.
one thought that i had was that we could set it up so that the graphql endpoint is only csrf protected in production.
so graphiql would work, but only in the staging environment and not in production.
WDYT?

2023-03-09 15:01 UTC, wgwz commented on sql/authn/R__get_current_account_id.sql
> +CREATE OR REPLACE FUNCTION public.get_current_account_id()
originally, `get_current_account` was doing a different type of lookup, which involved plpgsql code, rather than just vanilla SQL. i added `get_current_account_id` when i was modifying the basis of the user session's to be tied to account id rather than address. long story short, there's not really a great reason we have both. my intention though is that `get_current_account_id` is a lower-level helper function, whereas `get_current_account` is intended to be a part of an API we interact with more broadly 🤷

2023-03-09 15:18 UTC, blushi commented on sql/authn/R__get_current_account_id.sql
> +CREATE OR REPLACE FUNCTION public.get_current_account_id()
yeah I realized that too, but nothing shows this difference really directly in the code, unless we make `get_current_account_id` part of private schema for instance? or we get rid of `get_current_account_id` and just keep `get_current_account`, it might be less confusing

2023-03-09 15:19 UTC, wgwz commented on server/Server.ts
> +app.use('/graphql', doubleCsrfProtection);
alright so i just found this:

https://github.com/graphql/graphiql/blob/main/packages/graphiql/README.md#using-as-package

TL;DR we could add a task to basically serve up a custom graphiql instance, that would use CSRF tokens

2023-03-09 15:24 UTC, blushi commented on server/Server.ts
> +app.use('/graphql', doubleCsrfProtection);
I also saw this option: https://github1s.com/graphile/starter/blob/main/@app/server/src/middleware/installCSRFProtection.ts#L16-L28
they don't use the same csrf lib but I believe it could work with our setup too since our doubleCsrfProtection is just a request handler too
wdyt?

2023-03-09 16:45 UTC, wgwz commented on server/Server.ts
> +app.use('/graphql', doubleCsrfProtection);
hmm with that approach though i worry about there being a way around the csrf protection for the graphql endpoint because spoofing headers is trivial

2023-03-09 17:45 UTC, wgwz commented on sql/authn/R__get_current_account_id.sql
> +CREATE OR REPLACE FUNCTION public.get_current_account_id()
it looks like the `get_current_account_id` cannot be marked as private.
because that function needs to be run as "the user" to work correctly and also the user does not have access to the private schema.
if we upgraded that function to run as SECURITY DEFINER, it would break the system.
because `current_setting('account.id', true)` would always returns `null`.

i think we should keep these as is, unless we see a strong reason for changing it.
IMO it's just a function that calls another function and it's not too confusing.
`get_current_account_id` can remain as a public API, and it will return just the ID (i will mark it as STABLE).
`get_current_account` will be the public API for getting the whole account for the current user

2023-03-13 09:52 UTC, blushi commented on server/Server.ts
> +app.use('/graphql', doubleCsrfProtection);
that's a good point
then I guess we can just disable graphiql from postgraphile setup for now, and implement a custom instance as a follow up issue: https://github.com/regen-network/regen-registry/issues/1591

2023-03-13 17:27 UTC, wgwz commented on server/Server.ts
> +app.use('/graphql', doubleCsrfProtection);
i pushed a commit that disables graphiql by default
it can be enabled through an env var `GRAPHQL_ENABLED=true`
we'll need to set that in local and staging environments
i added a note about that too the `.env-example` as well

2023-03-14 20:08 UTC, merged