fix: use ssl for postgres image caching in production
regen-network/registry-server pull request #261
Opened 2022-12-05 22:33 UTC by wgwz

## Description

Closes: regen-network/regen-registry#1311

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted `dev` branch
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2022-12-06 08:49 UTC, blushi requested changes

2022-12-06 08:49 UTC, blushi commented on server/middleware/imageOptimizer.ts
> +      // connect to it. whereas the staging database does not. arguably,
the staging db does need an ssl certificate, NODE_ENV is still equal to `production` on the staging server by default (https://devcenter.heroku.com/changelog-items/688) so this comment is wrong
that's the local development db that does not need it

2022-12-06 08:49 UTC, blushi commented on server/middleware/imageOptimizer.ts
> +        imageCache = new Keyv(process.env.DATABASE_URL, {
I think it would be best to use a different db than the one we already use for storing user/business specific data

2022-12-06 14:33 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +      // connect to it. whereas the staging database does not. arguably,
it works in staging though, w/o these changes, that was one of the surprises.

2022-12-06 15:14 UTC, blushi commented on server/middleware/imageOptimizer.ts
> +        imageCache = new Keyv(process.env.DATABASE_URL, {
yeah I meant creating a new database so the image caching load doesn't interfere with the rest
at least we shouldn't expose the keyv table in our graphql endpoint from postgraphile

2022-12-06 15:43 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +        imageCache = new Keyv(process.env.DATABASE_URL, {
it’s valid concern but i don’t think the load would be too much. here’s some related comment from when i initially added this: https://github.com/regen-network/registry-server/pull/241#issuecomment-1255631208

if we want to prevent unbounded growth of this cache, we can add a TTL. we could also enforce a max size for the number of cached items. 

but generally the number items we are caching here is the total sum of the number of variations in dimensions for each image we are pulling from S3 from the UI.

i think that number is far smaller than max capacities for postgres from a performance standpoint.

definitely, agreed on separating this out of the postgraphile schema. but i’m tending to diasgree with spinning up a new database instance for this (if that’s what you meant). postgres is a super performant and optimized tool, it should be able handle this w/o issue.

2022-12-13 16:09 UTC, blushi commented on server/middleware/imageOptimizer.ts
> +        imageCache = new Keyv(process.env.DATABASE_URL, {
as discussed during our 1-1, ok with the separate db schema option

2022-12-15 21:13 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +      // connect to it. whereas the staging database does not. arguably,
i've made this comment more accurate and i added a link as well to a relevant part of the AWS RDS docs regarding this.

2022-12-15 21:16 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +        imageCache = new Keyv(process.env.DATABASE_URL, {
i moved this into a new schema called `utilities` and adjusted the keyv caching solution to use the `utilities.key` table for it's cache, i.e.:

![Screen Shot 2022-12-15 at 4 14 43 PM](https://user-images.githubusercontent.com/10120306/207968541-b83cbeff-b0dc-41df-95f4-94d01b7c8ffe.jpg)

if there is a better name for the schema, i'm open to suggestions and changing that. i wanted to keep it general in case there are other things we would like to use it for.

also i doubled-checked that postgraphile is not serving this table (it's only serving tables in `public`)

2022-12-15 21:29 UTC, wgwz commented
Hey @mhagel just wanted to provide you a little context here. The high-level result of merging this will be that we will not run out of space with redis for image caching anymore. We'll switch production registry-server to use postgres as the storage backend. This PR in particular adds configuration line to connect to our production postgres, a "ca" certificate. The library we're using `@keyv/postgres` also needed an update. And Marie and I decided to move this new `keyv` table into it's own postgres schema (`utilities`) just for separation of concerns, and so that postgraphile doesn't serve the cache data as graphql.

2023-01-04 09:49 UTC, blushi commented on server/middleware/imageOptimizer.ts
> +      // verify-ca. arguably, we might want to impose the same restriction in
humm I thought the prod and staging dbs did have the same setup

2023-01-04 16:39 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +        imageCache = new Keyv(process.env.DATABASE_URL, {
i was only seeing two errors in my IDE, they were both just a missing type for a string (fixed those here 0a87c11). but i'm curious to know how you are seeing these other errors, so i can try to fix my IDE to show me these as well.

2023-01-04 17:14 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +      // verify-ca. arguably, we might want to impose the same restriction in
i just checked the parameter groups for these databases and they are using the same parameter group, so this comment is inaccurate, will fix.

2023-01-04 18:16 UTC, wgwz commented on server/middleware/imageOptimizer.ts
> +      // verify-ca. arguably, we might want to impose the same restriction in
updated my comment: 9ff6031

2023-01-05 07:50 UTC, blushi approved these changes

2023-01-17 20:41 UTC, merged