feat: graphile-migrate PoC
regen-network/registry-server pull request #324
Opened 2023-05-08 21:10 UTC by wgwz

## Description

Closes: https://github.com/regen-network/regen-registry/issues/1640

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted `dev` branch
- [x] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] submit a PR against `master` branch after this one (and other PRs depending on this one, e.g. on regen-network/regen-web, if applicable) get merged

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

2023-05-17 20:57 UTC, wgwz commented
importantly, all our e2e tests for the auth system are passing:
https://github.com/regen-network/registry-server/tree/kyle/1071-update-passportjs/server/__tests__/e2e

2023-05-22 09:18 UTC, blushi requested changes
thanks for this, I believe graphile-migrate will be a better migration tool for us
here's a few requested changes
let's also rm `FLYWAY_URL` and `FLYWAY_PASSWORD` from .env.example and mention of `FLYWAY_URL` in registryServer.yml

2023-05-22 09:18 UTC, blushi commented on migrations/README.md
> +The migrations are always automatically run in CI for staging and production.
strictly speaking it's run as part of heroku release phase https://devcenter.heroku.com/articles/release-phase, see Profile
we'll need to make sure DATABASE_URL, SHADOW_DATABASE_URL and ROOT_DATABASE_URL are set up there

2023-05-22 13:35 UTC, wgwz commented on migrations/initial_schema.sql
> +CREATE TABLE public.flyway_schema_history (
i'll add a migration to remove this, as well as some of those unused types, i think it will have to stay in this initial_schema though

2023-05-22 13:37 UTC, wgwz commented on migrations/README.md
> +The migrations are always automatically run in CI for staging and production.
good point, i was just being loose in the description. but actually for staging and production, we will only need the `DATABASE_URL`. because we only need one command for those environments, `graphile-migrate  migrate`. that command only requires the one.

2023-05-22 13:41 UTC, wgwz commented on .github/workflows/registryServer.yml
> +        run: sleep 20 && yarn test
yeah, so the server in the previous command takes some time to start up. if we start the tests before the server is running, now that we have e2e tests which require a server to run the tests against, we'll connection errors. this was an arbitrary amount of time that i added which seemed to remove most of flakiness related to this. so no, 20 seconds might always be enough, but most of the time it should be. i guess we could always use something like this instead:
https://www.npmjs.com/package/wait-port

2023-05-22 13:54 UTC, wgwz commented on .github/workflows/registryServer.yml
> +        run: sleep 20 && yarn test
142fb2fe0f904898a6591179824025513a70a807

2023-05-22 13:55 UTC, blushi commented on .github/workflows/registryServer.yml
> +        run: sleep 20 && yarn test
yeah that was my guess, thanks for the explanation
it would be nice to use wait-port indeed, could you add a tech task to work on that? we do not necessarily need to prioritize it for now, but good to keep track of that

2023-05-22 13:55 UTC, wgwz commented on sql/README.md
> +# Deprecated
bd3bdd20445d818299574a751f7d90ce70fd7d99

2023-05-22 14:12 UTC, wgwz commented on migrations/initial_schema.sql
> +CREATE TABLE public.flyway_schema_history (
i'm just basing that off of the instructions for using graphile-migrate with an existing database:
https://github.com/graphile/migrate#using-migrate-with-an-existing-database

i suppose there's probably a way to avoid it or clear it at a later time (like a rebase or something), but it seems easier to just go with it.

2023-05-22 15:35 UTC, blushi commented on migrations/initial_schema.sql
> +CREATE TABLE public.flyway_schema_history (
oh right, probably safer to rm it as part of a separate migration then!

2023-05-22 18:38 UTC, wgwz commented
> TODO:
> 
> > We recommend dumping your database schema with pg_dump after migrations are completed; you can [see an example of this in Graphile Starter](https://github.com/graphile/starter/blob/4854f77e461062a95cdfff9c62082eb90a3a0d5b/%40app/db/.gmrc#L20). Tracking this file in git will allow you to easily see the changes that different migrations are making, so you can be sure you're making the changes you intend to. We recommend that you dump the shadow database as it will be unaffected by the iteration you've been applying to your development database (which may have come out of sync - see 'Drift' below).
> 
> See [graphile/migrate#setup](https://github.com/graphile/migrate#setup), I think this will be nice to have

ok, i took care of this todo item
@blushi can you take a look and let me know WDYT? ff93c5d
i updated the `migrations/README.md` in that commit to try to explain this a bit
i'm a bit worried that this could be confusing but i think this could be a nice thing to have

2023-05-22 19:53 UTC, wgwz commented on migrations/initial_schema.sql
> +CREATE TABLE public.flyway_schema_history (
flyway table remove via: 1cc310f9d4184c1ec1425b69f0e5be5d37a693c7
some unused types cleanup: 4a188bd3366909b7393be320924aefbeced99ca7

2023-05-24 17:48 UTC, merged