Migration finally worked! :D
regen-network/registry-server pull request #34
Opened 2021-03-04 01:12 UTC by haveanicedavid

Migrations for https://github.com/regen-network/regen-registry/issues/351 and https://github.com/regen-network/regen-registry/issues/352

Migration runs successfully, but some of the sql functions might still need to be updated (see comments)

2021-03-04 01:19 UTC, haveanicedavid commented on sql/R__create_project.sql
> +    (org_name, wallet_addr, v_user.id, roles, org_address);-- TODO: (adding comment so it shows in diff - remove after clarified) Does this function need to be updated to reflect changes to `public.r
(text from comment): 
> Does this function need to be updated to reflect changes to `public.really_create_organization? Two arguments (legal_name and logo) aren't nullable, so i'm not sure how i'd fill them in here... would I use the user's name and image?

If so, will the user's image being nullable create any issue?

2021-03-09 08:45 UTC, blushi reviewed
Looks good so far, you now need to update `really_create_user` and `really_create_organization` functions logic to account for the new columns.

2021-03-09 08:45 UTC, blushi commented on sql/R__create_org.sql
> +  legal_name text,
you might need to add `drop function if exists public.really_create_organization;`, else that might result in 2 different functions with the same name but different parameters. 
If you've run the migrations `drop function if exists public.really_create_organization;` will probably fail because it won't know which function to drop.

You can use the following to display the `DROP FUNCTION` commands to run to drop all the functions with a given name:

```sql
SELECT format('DROP FUNCTION %I.%I(%s);'
            , n.nspname
            , p.proname
            , pg_catalog.pg_get_function_identity_arguments(p.oid)
             ) AS stmt
FROM pg_catalog.pg_proc p
  JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE  p.proname = 'really_create_organization' AND n.nspname = 'public';
```
So you'll need to execute that before you re-run the migrations.

2021-03-09 08:45 UTC, blushi commented on sql/R__create_project.sql
> +    (org_name, wallet_addr, v_user.id, roles, org_address);-- TODO: (adding comment so it shows in diff - remove after clarified) Does this function need to be updated to reflect changes to `public.r
you can just use empty strings for now.
On the client side, this function is used to create a new buyer from the admin interface and when purchasing credits (though the latter is not enabled yet) so eventually we'll need to update those interfaces to reflect those new required fields.

2021-03-09 08:53 UTC, blushi commented
Regarding `really_create_organization_if_needed` & `really_create_user_if_needed`, I think you can just leave them as is, ie no need to add new parameters but you'll need to update their implementation when the modified functions `really_create_organization` & `really_create_user` are called.
To ensure that you haven't forget anything, I would recommend to update existing tests and/or add new ones.

2021-04-13 08:32 UTC, blushi requested changes
Looks good overall!
Though I ran into a few issues when running the migrations locally, which is kind of tricky and due to the fact that I ran them all at once, while you wrote one then run it, wrote the next one, run it, etc.

- First I was getting this:
```

Caused by: 
Migration V1_59__user_org_party_update_perms.sql failed
-------------------------------------------------------
SQL State  : 42883
Error Code : 0
Message    : ERROR: function public.get_current_user_id() does not exist
  Indice : No function matches the given name and argument types. You might need to add explicit type casts.
Location   : sql/V1_59__user_org_party_update_perms.sql (/Users/mariegauthier/regen/regen-network-mvp/sql/V1_59__user_org_party_update_perms.sql)
Line       : 12
Statement  : create policy owner_update_organization on organization
  for update using (
    exists(
      select 1
      from organization_member
      inner join "user" on organization_member.member_id = "user".id
      where organization_member.organization_id = organization.id
      and member_id = public.get_current_user_id()
      and is_owner is true
    )
  )

Caused by: org.postgresql.util.PSQLException: ERROR: function public.get_current_user_id() does not exist
```
This is due to the fact that flyway first runs the versioned migrations before the repeatable migrations so it couldn't find the new function `get_current_user_id`

- The second issue I ran into:
```
ERROR: cannot change name of input parameter "avatar"
  Indice : Use DROP FUNCTION create_user_organization_if_needed(text,text,text,text,text,text[],jsonb,boolean) first.
````
It does seem like you need to add `drop function if exists ...` when changing a function parameter name.

So I've created this small PR against your branch with some fixes: https://github.com/regen-network/registry-server/pull/49, please review and merge into your branch if this makes sense.

2021-04-20 01:04 UTC, haveanicedavid commented
@blushi I merged in your code fixes and removed comments - re-requesting review

2021-04-20 07:02 UTC, blushi requested changes
Looks good overall, just one comment to address.
Let's make sure to add tests later on as part of https://github.com/regen-network/regen-registry/issues/352

2021-04-20 18:56 UTC, mhagel approved these changes
Approved, pending Marie's change request

2021-04-21 03:59 UTC, haveanicedavid commented on sql/R__create_org.sql
> +  legal_name text,
@blushi I believe both of these should now be addressed

2021-04-21 04:02 UTC, haveanicedavid commented on sql/R__create_project.sql
> +    (name, wallet_addr, v_user.id, org_name, image, roles, org_address);
@blushi I changed the order of these while trying to fix the tests. I believe the `really_create_organization` function is set up to accept the normal (non-legal) `name` as the first argument, but wanted to make sure you noticed

2021-04-21 09:56 UTC, blushi requested changes

2021-04-21 09:56 UTC, blushi commented on sql/R__create_project.sql
> +    (name, wallet_addr, v_user.id, org_name, image, roles, org_address);
here `name` is the user name so this is wrong, let's just use `org_name` for both normal and legal names

2021-04-21 15:32 UTC, blushi approved these changes

2021-04-21 15:33 UTC, merged