Add metadata field to retire_credits function
regen-network/registry-server pull request #89
Opened 2021-09-14 06:12 UTC by haveanicedavid

references: regen-network/regen-registry#646
[Frontend PR](

2021-09-14 08:08 UTC, blushi requested changes

2021-09-14 08:08 UTC, blushi commented on sql/R__retire_credits.sql
> +  metadata jsonb
```suggestion
  metadata jsonb default '{}'
```

2021-09-14 08:08 UTC, blushi commented on sql/R__transfer_credits.sql
> +    perform retire_credits(vintage_id, buyer_wallet_id, address_id, units, default);
this makes the tests fail, if you apply the change from above, you should be able to just use:
```suggestion
    perform retire_credits(vintage_id, buyer_wallet_id, address_id, units);
```

2021-09-14 23:57 UTC, haveanicedavid commented on sql/R__retire_credits.sql
> +  metadata jsonb
This fixed an issue I kept bumping into and makes sense after reading through docs - thank you!

2021-09-14 23:57 UTC, haveanicedavid commented
@blushi just updated - tests now pass

2021-09-15 07:37 UTC, blushi approved these changes
Approving now that I've changed the base branch to be `dev`, please make sure to submit registry-server PRs against `dev` first.

2021-09-15 18:05 UTC, mhagel approved these changes

2021-09-17 04:39 UTC, merged